Add additional checks to linting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,21 +4,61 @@ on:
   push:
     paths:
       - '.github/workflows/ci.yml'
-      #- 'patches/*'
+      - 'patches/*' #.toml
       - '.eslintrc.js'
   pull_request:
-    paths:
-      - '.github/workflows/ci.yml'
-      - 'patches/*'
-      - '.eslintrc.js'
+    #paths:
+    #  - '.github/workflows/ci.yml'
+    #  - 'patches/*' #.toml
+    #  - '.eslintrc.js'
   workflow_dispatch:
 
 jobs:
   lint:
     runs-on: ubuntu-latest
-    steps: # TODO: Check patch filenames
+    steps:
       - uses: actions/checkout@v2
       - name: Setup
         run: npm i -D --no-fund eslint eslint-plugin-toml
       - name: Lint
-        run: npx eslint patches --ext .toml
+        run: |
+          npx eslint patches/*.toml
+          function patches_invalidate() {
+            patches_invalid_reasons+=$'\n'"$1"$'\n'
+          }
+          for file in patches/*; do
+            file_content="$(cat "${file}")"
+            file_name="${file//patches\/}"
+            if [[ ! "$file_name" =~ ^[0-9A-F]{8}\ -\ .+\.toml$ ]]; then
+              patches_invalid_filename+=$'\n'" $file_name"
+            fi
+            if [[ "$file_content" =~ 'is_enabled = true' ]]; then
+              patches_is_enabled+=$'\n'" $file_name"
+            fi
+            # Desc is optional
+            patch_required_info=({title_name,title_id,hash}\ =\ \" "[[patch]]" \ \ \ \ {{name,author}\ =\ \",is_enabled\ =\ ,\ \ \ \ {address,value}\ =\ })
+            for field in "${patch_required_info[@]}"; do
+              if [[ ! "$file_content" =~ "$field" ]]; then
+                if [[ ! "$patches_fields_missing" =~ $file_name ]]; then
+                  patches_fields_missing+=$'\n'" $file_name:"
+                fi
+                patches_fields_missing+=$'\n'"  $field"
+              fi
+            done
+          done
+          if [ -n "$patches_invalid_filename" ]; then
+            patches_invalidate "These patch filename(s) are invalid;$patches_invalid_filename"
+          fi
+          if [ -n "$patches_is_enabled" ]; then
+            patches_invalidate "These patches are enabled;$patches_is_enabled"
+          fi
+          if [ -n "$patches_fields_missing" ]; then
+            patches_invalidate "These patches are missing required info;$patches_fields_missing"
+          fi
+          if [ -z "$patches_invalid_reasons" ]; then
+            echo 'Lint succeeded!'
+          else
+            patches_invalid_reasons="${patches_invalid_reasons/#$'\n'}"
+            echo "${patches_invalid_reasons/%$'\n'}"
+            exit 1
+          fi
